baseURL = "https://hebammejutta.at"
canonifyURLs = true
languageCode = "de-de"
title = "Hebamme Jutta Wehinger"
theme = "story"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
subtitle = "Vor und nach der Geburt: Deine Reise mit einer Hebamme voller Fürsorge und Erfahrung in Dornbirn, Lustenau und Umgebung."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
[[module.imports]]
    path = 'github.com/gethugothemes/hugo-modules/modal'

[[params.plugins.js]]
link = "js/modal.js"